import { Inter } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Colophon from "@/components/Colophon/Colophon";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <div className="flex flex-col min-h-screen">
            <Header locale={locale} />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Colophon />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}